### ISSUE TITLE
Rejected by App Review team 

### ISSUE THREAD

**Issue by kevwkev** [naluinui/EggRating#7]
Guideline 1.1.7 - Safety - Objectionable Content

“We noticed that your app includes content and features that can manipulate the user reviews or chart ranking on the App Store. Specifically, your app filters user reviews and only directs users who intend to rate your app 4 - 5 stars to complete a rating on the App Store.”

**Comment by sonictunes** [comment]
This is super interesting. Do you have a screenshot of what they rejected / what filter they're referring to?

**Comment by revg75** [comment]
Same rejection happened to me as well.

**Comment by borneadmin** [comment]
Same here. Should have checked issues before submitting...

**Comment by naluinui** [comment]
Really sorry for that guys! This library was a bit cheeky and Apple has noticed it 😅For anyone who still wants a tool for ratings and reviews, please use the official one from Apple instead: https://developer.apple.com/app-store/ratings-and-reviews/
