### ISSUE TITLE
rejected appstore

### ISSUE THREAD

**Issue by zezeron** [naluinui/EggRating#8]
my application has been rejected because I use "import EggRating" 

I wasn't actually using it. However, I still think it is rejected automatically because of EGGRATING.
![screen shot 2018-11-09 at 11 32 36](https://user-images.githubusercontent.com/1241517/48251591-3638be00-e413-11e8-8065-882c21f94869.png)

**Comment by revg75** [comment]
Yep same happened to me

**Comment by dungntm58** [comment]
Same as me :(

**Comment by naluinui** [comment]
Really sorry for that guys! This library was a bit cheeky and Apple has noticed it 😅For anyone who still wants a tool for ratings and reviews, please use the official one from Apple instead: https://developer.apple.com/app-store/ratings-and-reviews/
